name: API Tests

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: gradle:8.5-jdk17

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: gradle clean test

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: build/allure-results

  publish-report:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate report 
        uses: simple-elf/allure-report-action@master 
        with: 
          gh_pages: gh-pages
          allure_results: allure-results 
          allure_report: allure-report
      
      - name: Deploy to GitHub Pages 
        uses: peaceiris/actions-gh-pages@v4   
        with:   
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          publish_branch: gh-pages
          publish_dir: allure-history
         
