name: API Tests

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: gradle:8.5-jdk17

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: gradle clean test

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: build/allure-results

  publish-report:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

       - name: Generate Allure report
        run: |
          wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.0/allure-commandline-2.24.0.zip
          unzip allure-commandline-2.24.0.zip
          ./allure-2.24.0/bin/allure generate allure-results -o allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
